### ISSUE TITLE
PersonalDataConsents for both California and National Strings, should just be an integer and not list

### ISSUE THREAD

**Issue by srinivas81** [IABTechLab/iabgpp-java#7]
According to the [specs](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/US-States/CA/GPP%20Extension:%20IAB%20Privacy%E2%80%99s%20California%20Privacy%20Technical%20Specification.md) , PersonalDataConsents for both California and National strings should just be an integer, but the [code](https://github.com/IABTechLab/iabgpp-java/blob/master/iabgpp-encoder/src/main/java/com/iab/gpp/encoder/section/UspCaV1.java#L45) is treating it as a list of 2 integers.

**Comment by chuff** [comment]
Fixed in 3.0.3
